[project]
name = "mlzoomcamp"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "awsebcli>=3.27.3",
    "fastapi>=0.141.1",
    "flask>=3.1.3",
    "gunicorn>=26.2.0",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.9",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "onnx>=1.22.0",
    "onnxscript>=0.7.2",
    "pandas>=3.0.5",
    "pandas-stubs~=3.0.5",
    "podman>=5.8.0",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.0",
    "uvicorn>=0.52.4",
    "xgboost>=3.4.1",
]
